CHECKPOINT_DIR: "/snel/share/joel/transformer_modeling/"
DATA:
  DATAPATH: "/snel/share/data/nlb/"
  TRAIN_FILENAME: 'mc_maze_small.h5'
  VAL_FILENAME: 'mc_maze_small.h5'
MODEL:
  TRIAL_LENGTH: 0 # 140
  LEARNABLE_POSITION: True
  PRE_NORM: True
  FIXUP_INIT: True
  EMBED_DIM: 0
  LOGRATE: True
  NUM_LAYERS: 4
TRAIN:
  LR:
    WARMUP: 2000
  MASK_RATIO: 0.25
  WEIGHT_DECAY: 5.0e-05
  PATIENCE: 2000
  LOG_INTERVAL: 200
  VAL_INTERVAL: 20
  CHECKPOINT_INTERVAL: 1000
  NUM_UPDATES: 50501
  MASK_SPAN_RAMP_START: 5000
  MASK_SPAN_RAMP_END: 10000

  TUNE_HP_JSON: './configs/mc_maze.json' # This space has more aggressive regularization
